---
apiVersion: "cilium.io/v2alpha1"
kind: CiliumBGPPeeringPolicy
metadata:
 name: 01-bgp-peering-policy
spec: # CiliumBGPPeeringPolicySpec
 nodeSelector:
   matchLabels:
     bgp-policy: istio
 virtualRouters: # []CiliumBGPVirtualRouter
 - localASN: 64504
   exportPodCIDR: true
   neighbors: # []CiliumBGPNeighbor
    - peerAddress: '172.18.255.251/16'
      peerASN: 65100
      eBGPMultihopTTL: 10
      connectRetryTimeSeconds: 120
      holdTimeSeconds: 90
      keepAliveTimeSeconds: 30
      gracefulRestart:
        enabled: true
        restartTimeSeconds: 120