---
apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
spec:
  selector:
    app: nginx
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 4335
      appProtocol: tls
      targetPort: 4335
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.25.1-alpine
        ports:
        - containerPort: 4335
        volumeMounts:
        - name: nginx-conf
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
        - name: nginx-example-tls
          mountPath: /etc/nginx/tls/nginx.crt
          subPath: tls.crt
        - name: nginx-example-tls
          mountPath: /etc/nginx/tls/nginx.key
          subPath: tls.key
      volumes:
      - name: nginx-conf
        configMap:
          name: nginx-conf
      - name: nginx-example-tls
        secret:
          secretName: nginx-example-tls
