apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: helloworld-global
spec:
  hosts:
  - helloworld.global
  ports:
  - number: 5000
    name: tcp
    protocol: TCP
  location: MESH_INTERNAL
  resolution: DNS
  endpoints:
  - address: helloworld.default.svc.cluster.local
