apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: to-kind-clu2
  namespace : default
spec:
  hosts:
  - *.clu2foo.example.test
  - *.clu2bar.example.test
  - *.clu2default.example.test
  location: MESH_INTERNAL
  ports:
  - number: 8080
    name: http
    protocol: HTTP
  - number: 8081
    name: http
    protocol: HTTP
  resolution: STATIC
  endpoints:
  - address: 172.18.255.121