apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: "deny-port-15433"
  namespace: istio-system
spec:
  endpointSelector:
    matchLabels:
      istio: eastwestgateway
  ingress:
  - toPorts:
    - ports:
      - port: "15433"
        protocol: TCP

