apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: to-kind-clu2
  namespace : default
spec:
  hosts:
  - *.foo.kindclu2.test
  - *.bar.kindclu2.test
  - *.default.kindclu2.test
  location: MESH_INTERNAL
  ports:
  - number: 8080
    name: http
    protocol: HTTP
  - number: 8081
    name: http
    protocol: HTTP
  resolution: STATIC
  endpoints:
  - address: 172.18.255.121
    ports:
      http: 80