apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: httpbin-svc
spec:
  host: httpbin.default.svc.cluster.local
  trafficPolicy:
    loadBalancer:
      consistentHash:
        useSourceIp: true
      localityLbSetting:
        enabled: false