version: "3.9"
services:
    frr:
        image: frrouting/frr:v8.5.3
        hostname: frr01
        container_name: frr01
        network_mode: host
        restart: always
        volumes:
          - frr_config:/etc/frr
        privileged: true

volumes:
  frr_config:
    driver: local