kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
networking:
  ipFamily: dual
  podSubnet: "2001:192:168:0::/56,10.244.0.0/16"
  serviceSubnet: "2001:192:168:1::/112,10.96.0.0/12"
nodes:
- role: control-plane
- role: worker
- role: worker