kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
- role: worker
- role: worker
networking:
  ipFamily: ipv4  #default is ipv4
  disableDefaultCNI: true
  podSubnet: "10.25.0.0/16" # default value is "10.244.0.0/16"
  serviceSubnet: "10.35.0.0/16" # default value is "10.96.0.0/12"